[package]
name = "factorion-bot"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.12.8", features = ["json"] }
serde = { version = "^1.0.200", features = ["derive"] }
serde_json = "^1.0.116"
regex = "^1.10.4"
tokio = { version = "^1.37.0", features = ["full"] }
num-bigint = "^0.4.4"
num-traits = "^0.2.18"
base64 = "^0.22.1"
dotenv = "^0.15.0"
time = "0.3.36"
